import './globals.css'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'

const nunitoSans = Nunito_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Countries List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <main className='bg-gray-100 min-h-screen flex flex-col items-center'>
          <nav className='w-full bg-white h-16 flex items-center justify-center'>
            <section className='container flex'>
              <Link className="flex flex-row items-center gap-3" href={"/"}>
                <Image 
                  width={48}
                  height={48}
                  src='/logo.jpeg' 
                  alt='logo da aplicação' 
                />
                <h1 className='font-bold text-2xl'>Countries List</h1>
              </Link>
            </section>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
